#!/usr/bin/env python3
"""
ICH Guidelines Proxy — auto-generated by MoltProxy.

Domain: ich.org
Tools: 7
Generated from MoltBook config.

Usage:
    echo '{"tool": "tool-name", "args": {}}' | python3 ich_org_proxy.py
"""

from __future__ import annotations

import json
import sys
import urllib.error
import urllib.parse
import urllib.request


import json

def ensure_str(val) -> str:
    """Coerce any input to string safely to prevent AttributeError."""
    if val is None:
        return ""
    if isinstance(val, (int, float, bool)):
        return str(val)
    if isinstance(val, (list, dict)):
        try:
            return json.dumps(val)
        except Exception:
            return str(val)
    return str(val)

def get_int_param(args: dict, key: str, default: int, min_val: int = None, max_val: int = None) -> int:
    """Safely parse integer parameter with optional clamping."""
    val = args.get(key)
    if val is None:
        return default
    try:
        res = int(val)
    except (ValueError, TypeError):
        return default
    if min_val is not None:
        res = max(res, min_val)
    if max_val is not None:
        res = min(res, max_val)
    return res




def _launch_browser():
    """Launch Playwright headless browser."""
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        return None, None, None
    pw = sync_playwright().start()
    browser = pw.chromium.launch(headless=True)
    page = browser.new_page()
    return pw, browser, page

BASE_URL = "https://ich.org"
DATA_SOURCE = "ich.org"
USER_AGENT = "NexVigilant-Station/1.0 (PV research tool)"
TIMEOUT = 15


def search_guidelines(args: dict) -> dict:
    """Search ICH guidelines by topic, code, or keyword"""
    query = ensure_str(args.get("query", "")).strip()
    if not query:
        return {"status": "error", "message": "query is required"}
    category = args.get("category", "")

    pw, browser, page = _launch_browser()
    if pw is None:
        return {"status": "error", "message": "playwright not installed"}

    try:
        page.goto(BASE_URL, timeout=30000, wait_until="domcontentloaded")
        page.wait_for_timeout(3000)

        # Add CSS selectors for this tool when DOM solidifies
        # page.fill("selector", param_value)
        # page.click("selector")
        # results = page.query_selector_all("selector")

        page_text = page.inner_text("body")
        return {
            "status": "ok",
            "data": {"page_text_length": len(page_text)},
            "data_source": DATA_SOURCE,
        }
    except Exception as e:
        return {"status": "error", "message": str(e)}
    finally:
        browser.close()
        pw.stop()


def get_guideline(args: dict) -> dict:
    """Get ICH guideline summary and current step by code"""
    code = ensure_str(args.get("code", "")).strip()
    if not code:
        return {"status": "error", "message": "code is required"}

    pw, browser, page = _launch_browser()
    if pw is None:
        return {"status": "error", "message": "playwright not installed"}

    try:
        page.goto(BASE_URL, timeout=30000, wait_until="domcontentloaded")
        page.wait_for_timeout(3000)

        # Add CSS selectors for this tool when DOM solidifies
        # page.fill("selector", param_value)
        # page.click("selector")
        # results = page.query_selector_all("selector")

        page_text = page.inner_text("body")
        return {
            "status": "ok",
            "data": {"page_text_length": len(page_text)},
            "data_source": DATA_SOURCE,
        }
    except Exception as e:
        return {"status": "error", "message": str(e)}
    finally:
        browser.close()
        pw.stop()


def get_pv_guidelines(args: dict) -> dict:
    """Get all pharmacovigilance-related guidelines (E2x series)"""

    pw, browser, page = _launch_browser()
    if pw is None:
        return {"status": "error", "message": "playwright not installed"}

    try:
        page.goto(BASE_URL, timeout=30000, wait_until="domcontentloaded")
        page.wait_for_timeout(3000)

        # Add CSS selectors for this tool when DOM solidifies
        # page.fill("selector", param_value)
        # page.click("selector")
        # results = page.query_selector_all("selector")

        page_text = page.inner_text("body")
        return {
            "status": "ok",
            "data": {"page_text_length": len(page_text)},
            "data_source": DATA_SOURCE,
        }
    except Exception as e:
        return {"status": "error", "message": str(e)}
    finally:
        browser.close()
        pw.stop()


def get_meddra_guidelines(args: dict) -> dict:
    """Get MedDRA-related ICH guidelines and terminology references"""

    pw, browser, page = _launch_browser()
    if pw is None:
        return {"status": "error", "message": "playwright not installed"}

    try:
        page.goto(BASE_URL, timeout=30000, wait_until="domcontentloaded")
        page.wait_for_timeout(3000)

        # Add CSS selectors for this tool when DOM solidifies
        # page.fill("selector", param_value)
        # page.click("selector")
        # results = page.query_selector_all("selector")

        page_text = page.inner_text("body")
        return {
            "status": "ok",
            "data": {"page_text_length": len(page_text)},
            "data_source": DATA_SOURCE,
        }
    except Exception as e:
        return {"status": "error", "message": str(e)}
    finally:
        browser.close()
        pw.stop()


def get_safety_guidelines(args: dict) -> dict:
    """Get ICH Safety (S-series) guidelines — nonclinical safety pharmacology, carcinogenicity, genotoxicity, reproductive toxicology"""

    pw, browser, page = _launch_browser()
    if pw is None:
        return {"status": "error", "message": "playwright not installed"}

    try:
        page.goto(BASE_URL, timeout=30000, wait_until="domcontentloaded")
        page.wait_for_timeout(3000)

        # Add CSS selectors for this tool when DOM solidifies
        # page.fill("selector", param_value)
        # page.click("selector")
        # results = page.query_selector_all("selector")

        page_text = page.inner_text("body")
        return {
            "status": "ok",
            "data": {"page_text_length": len(page_text)},
            "data_source": DATA_SOURCE,
        }
    except Exception as e:
        return {"status": "error", "message": str(e)}
    finally:
        browser.close()
        pw.stop()


def get_quality_guidelines(args: dict) -> dict:
    """Get ICH Quality (Q-series) guidelines — stability testing, analytical validation, impurities, QbD, lifecycle management"""

    pw, browser, page = _launch_browser()
    if pw is None:
        return {"status": "error", "message": "playwright not installed"}

    try:
        page.goto(BASE_URL, timeout=30000, wait_until="domcontentloaded")
        page.wait_for_timeout(3000)

        # Add CSS selectors for this tool when DOM solidifies
        # page.fill("selector", param_value)
        # page.click("selector")
        # results = page.query_selector_all("selector")

        page_text = page.inner_text("body")
        return {
            "status": "ok",
            "data": {"page_text_length": len(page_text)},
            "data_source": DATA_SOURCE,
        }
    except Exception as e:
        return {"status": "error", "message": str(e)}
    finally:
        browser.close()
        pw.stop()


def get_e2b_data_elements(args: dict) -> dict:
    """Get ICH E2B(R3) ICSR data element categories — administrative info, patient data, drug info, reaction/event, narrative structure"""

    pw, browser, page = _launch_browser()
    if pw is None:
        return {"status": "error", "message": "playwright not installed"}

    try:
        page.goto(BASE_URL, timeout=30000, wait_until="domcontentloaded")
        page.wait_for_timeout(3000)

        # Add CSS selectors for this tool when DOM solidifies
        # page.fill("selector", param_value)
        # page.click("selector")
        # results = page.query_selector_all("selector")

        page_text = page.inner_text("body")
        return {
            "status": "ok",
            "data": {"page_text_length": len(page_text)},
            "data_source": DATA_SOURCE,
        }
    except Exception as e:
        return {"status": "error", "message": str(e)}
    finally:
        browser.close()
        pw.stop()


TOOL_DISPATCH = {
    "search-guidelines": search_guidelines,
    "get-guideline": get_guideline,
    "get-pv-guidelines": get_pv_guidelines,
    "get-meddra-guidelines": get_meddra_guidelines,
    "get-safety-guidelines": get_safety_guidelines,
    "get-quality-guidelines": get_quality_guidelines,
    "get-e2b-data-elements": get_e2b_data_elements,
}


def main() -> None:
    raw = sys.stdin.read().strip()
    if not raw:
        print(json.dumps({"status": "error", "message": "No input on stdin"}))
        sys.exit(1)

    try:
        payload = json.loads(raw)
    except json.JSONDecodeError as exc:
        print(json.dumps({"status": "error", "message": f"Invalid JSON: {exc}"}))
        sys.exit(1)

    tool_name = ensure_str(payload.get("tool", "")).strip()
    args = payload.get("arguments", payload.get("args", {}))

    if tool_name not in TOOL_DISPATCH:
        print(json.dumps({
            "status": "error",
            "message": f"Unknown tool '{tool_name}'. Known: {list(TOOL_DISPATCH.keys())}",
        }))
        sys.exit(1)

    result = TOOL_DISPATCH[tool_name](args)
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
