#!/usr/bin/env python3
"""
MedDRA Terminology Proxy — auto-generated by MoltProxy.

Domain: meddra.org
Tools: 7
Generated from MoltBook config.

Usage:
    echo '{"tool": "tool-name", "args": {}}' | python3 meddra_org_proxy.py
"""

from __future__ import annotations

import json
import sys
import urllib.error
import urllib.parse
import urllib.request


import json

def ensure_str(val) -> str:
    """Coerce any input to string safely to prevent AttributeError."""
    if val is None:
        return ""
    if isinstance(val, (int, float, bool)):
        return str(val)
    if isinstance(val, (list, dict)):
        try:
            return json.dumps(val)
        except Exception:
            return str(val)
    return str(val)

def get_int_param(args: dict, key: str, default: int, min_val: int = None, max_val: int = None) -> int:
    """Safely parse integer parameter with optional clamping."""
    val = args.get(key)
    if val is None:
        return default
    try:
        res = int(val)
    except (ValueError, TypeError):
        return default
    if min_val is not None:
        res = max(res, min_val)
    if max_val is not None:
        res = min(res, max_val)
    return res




def _launch_browser():
    """Launch Playwright headless browser."""
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        return None, None, None
    pw = sync_playwright().start()
    browser = pw.chromium.launch(headless=True)
    page = browser.new_page()
    return pw, browser, page

BASE_URL = "https://meddra.org"
DATA_SOURCE = "meddra.org"
USER_AGENT = "NexVigilant-Station/1.0 (PV research tool)"
TIMEOUT = 15


def search_terms(args: dict) -> dict:
    """Search MedDRA terms across all hierarchy levels (SOC, HLGT, HLT, PT, LLT)"""
    query = ensure_str(args.get("query", "")).strip()
    if not query:
        return {"status": "error", "message": "query is required"}
    level = args.get("level", "")

    pw, browser, page = _launch_browser()
    if pw is None:
        return {"status": "error", "message": "playwright not installed"}

    try:
        page.goto(BASE_URL, timeout=30000, wait_until="domcontentloaded")
        page.wait_for_timeout(3000)

        # Add CSS selectors for this tool when DOM solidifies
        # page.fill("selector", param_value)
        # page.click("selector")
        # results = page.query_selector_all("selector")

        page_text = page.inner_text("body")
        return {
            "status": "ok",
            "data": {"page_text_length": len(page_text)},
            "data_source": DATA_SOURCE,
        }
    except Exception as e:
        return {"status": "error", "message": str(e)}
    finally:
        browser.close()
        pw.stop()


def get_term_hierarchy(args: dict) -> dict:
    """Get the full MedDRA hierarchy path for a preferred term"""
    preferred_term = ensure_str(args.get("preferred_term", "")).strip()
    if not preferred_term:
        return {"status": "error", "message": "preferred_term is required"}

    pw, browser, page = _launch_browser()
    if pw is None:
        return {"status": "error", "message": "playwright not installed"}

    try:
        page.goto(BASE_URL, timeout=30000, wait_until="domcontentloaded")
        page.wait_for_timeout(3000)

        # Add CSS selectors for this tool when DOM solidifies
        # page.fill("selector", param_value)
        # page.click("selector")
        # results = page.query_selector_all("selector")

        page_text = page.inner_text("body")
        return {
            "status": "ok",
            "data": {"page_text_length": len(page_text)},
            "data_source": DATA_SOURCE,
        }
    except Exception as e:
        return {"status": "error", "message": str(e)}
    finally:
        browser.close()
        pw.stop()


def get_soc_terms(args: dict) -> dict:
    """List all Preferred Terms under a System Organ Class"""
    soc = ensure_str(args.get("soc", "")).strip()
    if not soc:
        return {"status": "error", "message": "soc is required"}

    pw, browser, page = _launch_browser()
    if pw is None:
        return {"status": "error", "message": "playwright not installed"}

    try:
        page.goto(BASE_URL, timeout=30000, wait_until="domcontentloaded")
        page.wait_for_timeout(3000)

        # Add CSS selectors for this tool when DOM solidifies
        # page.fill("selector", param_value)
        # page.click("selector")
        # results = page.query_selector_all("selector")

        page_text = page.inner_text("body")
        return {
            "status": "ok",
            "data": {"page_text_length": len(page_text)},
            "data_source": DATA_SOURCE,
        }
    except Exception as e:
        return {"status": "error", "message": str(e)}
    finally:
        browser.close()
        pw.stop()


def get_smq(args: dict) -> dict:
    """Get Standardised MedDRA Query terms for a safety topic"""
    smq_name = ensure_str(args.get("smq_name", "")).strip()
    if not smq_name:
        return {"status": "error", "message": "smq_name is required"}
    scope = args.get("scope", "")

    pw, browser, page = _launch_browser()
    if pw is None:
        return {"status": "error", "message": "playwright not installed"}

    try:
        page.goto(BASE_URL, timeout=30000, wait_until="domcontentloaded")
        page.wait_for_timeout(3000)

        # Add CSS selectors for this tool when DOM solidifies
        # page.fill("selector", param_value)
        # page.click("selector")
        # results = page.query_selector_all("selector")

        page_text = page.inner_text("body")
        return {
            "status": "ok",
            "data": {"page_text_length": len(page_text)},
            "data_source": DATA_SOURCE,
        }
    except Exception as e:
        return {"status": "error", "message": str(e)}
    finally:
        browser.close()
        pw.stop()


def get_hierarchy_overview(args: dict) -> dict:
    """Get complete MedDRA hierarchy structure — 5 levels (LLT→PT→HLT→HLGT→SOC) with counts, relationships, and multi-axiality"""

    pw, browser, page = _launch_browser()
    if pw is None:
        return {"status": "error", "message": "playwright not installed"}

    try:
        page.goto(BASE_URL, timeout=30000, wait_until="domcontentloaded")
        page.wait_for_timeout(3000)

        # Add CSS selectors for this tool when DOM solidifies
        # page.fill("selector", param_value)
        # page.click("selector")
        # results = page.query_selector_all("selector")

        page_text = page.inner_text("body")
        return {
            "status": "ok",
            "data": {"page_text_length": len(page_text)},
            "data_source": DATA_SOURCE,
        }
    except Exception as e:
        return {"status": "error", "message": str(e)}
    finally:
        browser.close()
        pw.stop()


def get_version_info(args: dict) -> dict:
    """Get MedDRA version information, biannual update cycle, and MSSO maintenance organization details"""

    pw, browser, page = _launch_browser()
    if pw is None:
        return {"status": "error", "message": "playwright not installed"}

    try:
        page.goto(BASE_URL, timeout=30000, wait_until="domcontentloaded")
        page.wait_for_timeout(3000)

        # Add CSS selectors for this tool when DOM solidifies
        # page.fill("selector", param_value)
        # page.click("selector")
        # results = page.query_selector_all("selector")

        page_text = page.inner_text("body")
        return {
            "status": "ok",
            "data": {"page_text_length": len(page_text)},
            "data_source": DATA_SOURCE,
        }
    except Exception as e:
        return {"status": "error", "message": str(e)}
    finally:
        browser.close()
        pw.stop()


def get_multiaxiality_guide(args: dict) -> dict:
    """Get MedDRA multi-axiality guidance — how PTs map to multiple SOCs with primary/secondary designation and impact on signal detection"""

    pw, browser, page = _launch_browser()
    if pw is None:
        return {"status": "error", "message": "playwright not installed"}

    try:
        page.goto(BASE_URL, timeout=30000, wait_until="domcontentloaded")
        page.wait_for_timeout(3000)

        # Add CSS selectors for this tool when DOM solidifies
        # page.fill("selector", param_value)
        # page.click("selector")
        # results = page.query_selector_all("selector")

        page_text = page.inner_text("body")
        return {
            "status": "ok",
            "data": {"page_text_length": len(page_text)},
            "data_source": DATA_SOURCE,
        }
    except Exception as e:
        return {"status": "error", "message": str(e)}
    finally:
        browser.close()
        pw.stop()


TOOL_DISPATCH = {
    "search-terms": search_terms,
    "get-term-hierarchy": get_term_hierarchy,
    "get-soc-terms": get_soc_terms,
    "get-smq": get_smq,
    "get-hierarchy-overview": get_hierarchy_overview,
    "get-version-info": get_version_info,
    "get-multiaxiality-guide": get_multiaxiality_guide,
}


def main() -> None:
    raw = sys.stdin.read().strip()
    if not raw:
        print(json.dumps({"status": "error", "message": "No input on stdin"}))
        sys.exit(1)

    try:
        payload = json.loads(raw)
    except json.JSONDecodeError as exc:
        print(json.dumps({"status": "error", "message": f"Invalid JSON: {exc}"}))
        sys.exit(1)

    tool_name = ensure_str(payload.get("tool", "")).strip()
    args = payload.get("arguments", payload.get("args", {}))

    if tool_name not in TOOL_DISPATCH:
        print(json.dumps({
            "status": "error",
            "message": f"Unknown tool '{tool_name}'. Known: {list(TOOL_DISPATCH.keys())}",
        }))
        sys.exit(1)

    result = TOOL_DISPATCH[tool_name](args)
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
