#!/usr/bin/env python3
"""
EudraVigilance Live (MoltBrowser) Proxy — auto-generated by MoltProxy.

Domain: eudravigilance-live.ema.europa.eu
Tools: 3
Generated from MoltBook config.

Usage:
    echo '{"tool": "tool-name", "args": {}}' | python3 eudravigilance_live_ema_europa_eu_proxy.py
"""

from __future__ import annotations

import json
import sys
import urllib.error
import urllib.parse
import urllib.request


def _launch_browser():
    """Launch Playwright headless browser."""
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        return None, None, None
    pw = sync_playwright().start()
    browser = pw.chromium.launch(headless=True)
    page = browser.new_page()
    return pw, browser, page

BASE_URL = "https://eudravigilance-live.ema.europa.eu"
DATA_SOURCE = "eudravigilance-live.ema.europa.eu"
USER_AGENT = "NexVigilant-Station/1.0 (PV research tool)"
TIMEOUT = 15


def extract_case_counts(args: dict) -> dict:
    """Extract actual ICSR case counts from the EudraVigilance OBIEE dashboard via headless browser. Returns total cases, serious/non-serious split, and raw table data."""
    drug = args.get("drug", "").strip()
    if not drug:
        return {"status": "error", "message": "drug is required"}

    pw, browser, page = _launch_browser()
    if pw is None:
        return {"status": "error", "message": "playwright not installed"}

    try:
        page.goto(BASE_URL, timeout=30000, wait_until="domcontentloaded")
        page.wait_for_timeout(3000)

        # TODO: Add CSS selectors for this tool
        # page.fill("selector", param_value)
        # page.click("selector")
        # results = page.query_selector_all("selector")

        page_text = page.inner_text("body")
        return {
            "status": "ok",
            "data": {"page_text_length": len(page_text)},
            "data_source": DATA_SOURCE,
        }
    except Exception as e:
        return {"status": "error", "message": str(e)}
    finally:
        browser.close()
        pw.stop()


def extract_soc_breakdown(args: dict) -> dict:
    """Extract System Organ Class breakdown with actual case counts from EudraVigilance dashboard. Returns per-SOC serious/non-serious counts."""
    drug = args.get("drug", "").strip()
    if not drug:
        return {"status": "error", "message": "drug is required"}

    pw, browser, page = _launch_browser()
    if pw is None:
        return {"status": "error", "message": "playwright not installed"}

    try:
        page.goto(BASE_URL, timeout=30000, wait_until="domcontentloaded")
        page.wait_for_timeout(3000)

        # TODO: Add CSS selectors for this tool
        # page.fill("selector", param_value)
        # page.click("selector")
        # results = page.query_selector_all("selector")

        page_text = page.inner_text("body")
        return {
            "status": "ok",
            "data": {"page_text_length": len(page_text)},
            "data_source": DATA_SOURCE,
        }
    except Exception as e:
        return {"status": "error", "message": str(e)}
    finally:
        browser.close()
        pw.stop()


def extract_demographics(args: dict) -> dict:
    """Extract age group and sex distribution from EudraVigilance dashboard. Returns actual demographic case counts."""
    drug = args.get("drug", "").strip()
    if not drug:
        return {"status": "error", "message": "drug is required"}

    pw, browser, page = _launch_browser()
    if pw is None:
        return {"status": "error", "message": "playwright not installed"}

    try:
        page.goto(BASE_URL, timeout=30000, wait_until="domcontentloaded")
        page.wait_for_timeout(3000)

        # TODO: Add CSS selectors for this tool
        # page.fill("selector", param_value)
        # page.click("selector")
        # results = page.query_selector_all("selector")

        page_text = page.inner_text("body")
        return {
            "status": "ok",
            "data": {"page_text_length": len(page_text)},
            "data_source": DATA_SOURCE,
        }
    except Exception as e:
        return {"status": "error", "message": str(e)}
    finally:
        browser.close()
        pw.stop()


TOOL_DISPATCH = {
    "extract-case-counts": extract_case_counts,
    "extract-soc-breakdown": extract_soc_breakdown,
    "extract-demographics": extract_demographics,
}


def main() -> None:
    raw = sys.stdin.read().strip()
    if not raw:
        print(json.dumps({"status": "error", "message": "No input on stdin"}))
        sys.exit(1)

    try:
        payload = json.loads(raw)
    except json.JSONDecodeError as exc:
        print(json.dumps({"status": "error", "message": f"Invalid JSON: {exc}"}))
        sys.exit(1)

    tool_name = payload.get("tool", "").strip()
    args = payload.get("arguments", payload.get("args", {}))

    if tool_name not in TOOL_DISPATCH:
        print(json.dumps({
            "status": "error",
            "message": f"Unknown tool '{tool_name}'. Known: {list(TOOL_DISPATCH.keys())}",
        }))
        sys.exit(1)

    result = TOOL_DISPATCH[tool_name](args)
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
