#!/usr/bin/env python3
"""
MoltProxy — Auto-generate proxy scripts from MoltBook configs.

Reads a config JSON and generates a working Python proxy script with:
- Tool dispatch table
- Parameter handling with drug/query alias normalization
- HTTP extraction stubs (urllib for APIs, Playwright for JS-heavy sites)
- stdin/stdout JSON protocol matching Station dispatch.py contract

Usage:
    python3 moltproxy_generate.py configs/new-site.json
    python3 moltproxy_generate.py configs/new-site.json --browser  # Playwright stubs
    python3 moltproxy_generate.py --from-url https://example.com   # Scaffold from URL

Output: scripts/{domain}_proxy.py (ready to wire into dispatch.py)
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from textwrap import dedent


import json

def ensure_str(val) -> str:
    """Coerce any input to string safely to prevent AttributeError."""
    if val is None:
        return ""
    if isinstance(val, (int, float, bool)):
        return str(val)
    if isinstance(val, (list, dict)):
        try:
            return json.dumps(val)
        except Exception:
            return str(val)
    return str(val)

def get_int_param(args: dict, key: str, default: int, min_val: int = None, max_val: int = None) -> int:
    """Safely parse integer parameter with optional clamping."""
    val = args.get(key)
    if val is None:
        return default
    try:
        res = int(val)
    except (ValueError, TypeError):
        return default
    if min_val is not None:
        res = max(res, min_val)
    if max_val is not None:
        res = min(res, max_val)
    return res




def slugify(domain: str) -> str:
    """Convert domain to Python-safe filename slug."""
    return re.sub(r"[^a-z0-9]+", "_", domain.lower()).strip("_")


def generate_proxy(config: dict, use_browser: bool = False) -> str:
    """Generate a proxy script from a MoltBook config."""
    domain = config.get("domain", "unknown")
    title = config.get("title", domain)
    tools = config.get("tools", [])
    slug = slugify(domain)

    # Header
    lines = [
        '#!/usr/bin/env python3',
        '"""',
        f'{title} Proxy — auto-generated by MoltProxy.',
        f'',
        f'Domain: {domain}',
        f'Tools: {len(tools)}',
        f'Generated from MoltBook config.',
        f'',
        f'Usage:',
        f'    echo \'{{"tool": "tool-name", "args": {{}}}}\' | python3 {slug}_proxy.py',
        '"""',
        '',
        'from __future__ import annotations',
        '',
        'import json',
        'import sys',
        'import urllib.error',
        'import urllib.parse',
        'import urllib.request',
        '',
    ]

    if use_browser:
        lines.extend([
            '',
            'def _launch_browser():',
            '    """Launch Playwright headless browser."""',
            '    try:',
            '        from playwright.sync_api import sync_playwright',
            '    except ImportError:',
            '        return None, None, None',
            '    pw = sync_playwright().start()',
            '    browser = pw.chromium.launch(headless=True)',
            '    page = browser.new_page()',
            '    return pw, browser, page',
            '',
        ])

    lines.extend([
        f'BASE_URL = "https://{domain}"',
        f'DATA_SOURCE = "{domain}"',
        'USER_AGENT = "NexVigilant-Station/1.0 (PV research tool)"',
        'TIMEOUT = 15',
        '',
        '',
    ])

    # Generate a function for each tool
    for tool in tools:
        name = tool.get("name", "unknown-tool")
        desc = tool.get("description", "No description")
        params = tool.get("parameters", [])
        fn_name = name.replace("-", "_")

        lines.append(f'def {fn_name}(args: dict) -> dict:')
        lines.append(f'    """{desc}"""')

        # Extract parameters
        required_params = [p for p in params if p.get("required")]
        optional_params = [p for p in params if not p.get("required")]

        for p in required_params:
            pname = p["name"]
            lines.append(f'    {pname} = ensure_str(args.get("{pname}", "")).strip()')
            lines.append(f'    if not {pname}:')
            lines.append(f'        return {{"status": "error", "message": "{pname} is required"}}')

        for p in optional_params:
            pname = p["name"]
            default = '""' if p.get("type") == "string" else "None"
            lines.append(f'    {pname} = args.get("{pname}", {default})')

        lines.append('')

        if use_browser:
            lines.extend([
                '    pw, browser, page = _launch_browser()',
                '    if pw is None:',
                '        return {"status": "error", "message": "playwright not installed"}',
                '',
                '    try:',
                '        page.goto(BASE_URL, timeout=30000, wait_until="domcontentloaded")',
                '        page.wait_for_timeout(3000)',
                '',
                '        # TODO: Add CSS selectors for this tool',
                '        # page.fill("selector", param_value)',
                '        # page.click("selector")',
                '        # results = page.query_selector_all("selector")',
                '',
                '        page_text = page.inner_text("body")',
                '        return {',
                '            "status": "ok",',
                '            "data": {"page_text_length": len(page_text)},',
                f'            "data_source": DATA_SOURCE,',
                '        }',
                '    except Exception as e:',
                '        return {"status": "error", "message": str(e)}',
                '    finally:',
                '        browser.close()',
                '        pw.stop()',
            ])
        else:
            lines.extend([
                '    try:',
                f'        # TODO: Implement API call for {name}',
                '        url = f"{BASE_URL}/api/endpoint"',
                '        req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})',
                '        resp = urllib.request.urlopen(req, timeout=TIMEOUT)',
                '        data = json.loads(resp.read().decode("utf-8"))',
                '        return {',
                '            "status": "ok",',
                '            "data": data,',
                f'            "data_source": DATA_SOURCE,',
                '        }',
                '    except urllib.error.HTTPError as e:',
                '        return {"status": "error", "message": f"HTTP {e.code}: {e.reason}"}',
                '    except Exception as e:',
                '        return {"status": "error", "message": str(e)}',
            ])

        lines.extend(['', ''])

    # Dispatch table
    lines.append('TOOL_DISPATCH = {')
    for tool in tools:
        name = tool.get("name", "unknown-tool")
        fn_name = name.replace("-", "_")
        lines.append(f'    "{name}": {fn_name},')
    lines.append('}')
    lines.append('')

    # Main function (stdin/stdout protocol)
    lines.extend([
        '',
        'def main() -> None:',
        '    raw = sys.stdin.read().strip()',
        '    if not raw:',
        '        print(json.dumps({"status": "error", "message": "No input on stdin"}))',
        '        sys.exit(1)',
        '',
        '    try:',
        '        payload = json.loads(raw)',
        '    except json.JSONDecodeError as exc:',
        '        print(json.dumps({"status": "error", "message": f"Invalid JSON: {exc}"}))',
        '        sys.exit(1)',
        '',
        '    tool_name = ensure_str(payload.get("tool", "")).strip()',
        '    args = payload.get("arguments", payload.get("args", {}))',
        '',
        '    if tool_name not in TOOL_DISPATCH:',
        '        print(json.dumps({',
        '            "status": "error",',
        '            "message": f"Unknown tool \'{tool_name}\'. Known: {list(TOOL_DISPATCH.keys())}",',
        '        }))',
        '        sys.exit(1)',
        '',
        '    result = TOOL_DISPATCH[tool_name](args)',
        '    print(json.dumps(result, indent=2))',
        '',
        '',
        'if __name__ == "__main__":',
        '    main()',
        '',
    ])

    return '\n'.join(lines)


def main() -> None:
    if len(sys.argv) < 2:
        print("Usage: python3 moltproxy_generate.py <config.json> [--browser]")
        print("       python3 moltproxy_generate.py --from-url <url>")
        sys.exit(1)

    use_browser = "--browser" in sys.argv

    if "--from-url" in sys.argv:
        idx = sys.argv.index("--from-url")
        if idx + 1 >= len(sys.argv):
            print("Error: --from-url requires a URL argument")
            sys.exit(1)
        url = sys.argv[idx + 1]
        # Generate a minimal scaffold config from URL
        from urllib.parse import urlparse
        parsed = urlparse(url)
        domain = parsed.netloc or parsed.path
        config = {
            "domain": domain,
            "title": f"{domain} (auto-scaffolded)",
            "tools": [
                {
                    "name": "get-content",
                    "description": f"Extract content from {domain}",
                    "parameters": [
                        {"name": "query", "type": "string", "required": True,
                         "description": "Search query or identifier"}
                    ],
                },
            ],
        }
    else:
        config_path = sys.argv[1]
        with open(config_path) as f:
            config = json.load(f)

    domain = config.get("domain", "unknown")
    slug = slugify(domain)
    script = generate_proxy(config, use_browser=use_browser)

    scripts_dir = Path(__file__).parent
    output_path = scripts_dir / f"{slug}_proxy.py"
    output_path.write_text(script)
    print(f"Generated: {output_path}")
    print(f"  Domain: {domain}")
    print(f"  Tools: {len(config.get('tools', []))}")
    print(f"  Mode: {'browser (Playwright)' if use_browser else 'API (urllib)'}")
    print(f"\nNext: wire into dispatch.py and test with:")
    print(f"  echo '{{\"tool\": \"{config['tools'][0]['name']}\", \"args\": {{}}}}' | python3 {output_path.name}")


if __name__ == "__main__":
    main()
